### ISSUE TITLE
Feature request: Document report columns

### ISSUE THREAD

**Issue by narcisgarcia** [keltia/dmarc-cat#4]
With dmarc-cat I see IP, Count, From, RFrom, RDKIM, RSPF columns for a Rua report, but I don't exactly understand the meaning of each one; Receiver MTA? Sender MTA/SMTP? Envelope From:? RSPF=none what means?

Thank you.

**Comment by keltia** [comment]
Fixed with 863c28fe23e52f52cce288fb953260146a963448.
