### ISSUE TITLE
gpgme.h missing on MacOs

### ISSUE THREAD

**Issue by warwickchapman** [keltia/dmarc-cat#6]
When attempting to install on MacOS Catalina after `brew install go`, the following occurs:

```
warwick@Warwicks-MacBook-Pro ~ % go get github.com/keltia/dmarc-cat
# github.com/proglottis/gpgme
go/src/github.com/proglottis/gpgme/data.go:4:11: fatal error: 'gpgme.h' file not found
 #include <gpgme.h>
          ^~~~~~~~~
1 error generated.
```

**Comment by keltia** [comment]
You need to install the gpgme library from another source (Homebrew, Macports, etc.).

**Comment by keltia** [comment]
For macOS it should work out of the box, if not please see #3.
